# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_carinfo_carsimage_iwantinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': '车信息管理', 'verbose_name_plural': '车信息管理'},
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='area',
            field=models.IntegerField(blank=True, choices=[(0, '思明区'), (7, '龙文区'), (3, '杏林区'), (2, '集美区'), (4, '海沧区'), (1, '湖里区'), (5, '翔安区'), (6, '芗城区')], null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_age',
            field=models.IntegerField(blank=True, choices=[(3, '5年以上'), (0, '1年以内'), (1, '1-3年'), (2, '3-5年')], null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_brand',
            field=models.IntegerField(blank=True, choices=[(0, '大众'), (1, '丰田'), (3, '别克'), (2, '本田')], null=True, verbose_name='牌子'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(1, '经典SUV'), (2, '经济实用'), (3, '热门练手'), (0, '面包车'), (4, '超值低价')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='iwantinfo',
            name='want_type',
            field=models.IntegerField(choices=[(1, '我要卖车'), (0, '我要买车')], verbose_name='类型'),
        ),
    ]
