# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191211_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '品牌管理',
                'verbose_name_plural': '品牌管理',
            },
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='car_brand',
        ),
        migrations.AddField(
            model_name='iwantinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='area',
            field=models.IntegerField(blank=True, choices=[(3, '杏林区'), (1, '湖里区'), (7, '龙文区'), (6, '芗城区'), (0, '思明区'), (4, '海沧区'), (5, '翔安区'), (2, '集美区')], null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_age',
            field=models.IntegerField(blank=True, choices=[(0, '1年以内'), (2, '3-5年'), (3, '5年以上'), (1, '1-3年')], null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='car/images/%Y/%m/', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(4, '超值低价'), (0, '面包车'), (1, '经典SUV'), (3, '热门练手'), (2, '经济实用')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='carsimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='car/images/%Y/%m/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='iwantinfo',
            name='want_type',
            field=models.IntegerField(choices=[(1, '我要卖车'), (0, '我要买车')], verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='car_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.CarInfo'),
        ),
    ]
