# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191211_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='first_letter',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='首字符'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='area',
            field=models.IntegerField(blank=True, choices=[(4, '海沧区'), (0, '思明区'), (5, '翔安区'), (3, '杏林区'), (1, '湖里区'), (2, '集美区'), (7, '龙文区'), (6, '芗城区')], null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_age',
            field=models.IntegerField(blank=True, choices=[(2, '3-5年'), (3, '5年以上'), (0, '1年以内'), (1, '1-3年')], null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(4, '超值低价'), (1, '经典SUV'), (2, '经济实用'), (3, '热门练手'), (0, '面包车')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='iwantinfo',
            name='want_type',
            field=models.IntegerField(choices=[(1, '我要卖车'), (0, '我要买车')], verbose_name='类型'),
        ),
    ]
