# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191211_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=15, verbose_name='价格范围')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '价格范围',
                'verbose_name_plural': '价格范围',
            },
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='area',
            field=models.IntegerField(blank=True, choices=[(5, '翔安区'), (7, '龙文区'), (4, '海沧区'), (0, '思明区'), (1, '湖里区'), (6, '芗城区'), (3, '杏林区'), (2, '集美区')], null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_age',
            field=models.IntegerField(blank=True, choices=[(0, '1年以内'), (2, '3-5年'), (1, '1-3年'), (3, '5年以上')], null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(2, '经济实用'), (4, '超值低价'), (0, '面包车'), (1, '经典SUV'), (3, '热门练手')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='iwantinfo',
            name='want_type',
            field=models.IntegerField(choices=[(0, '我要买车'), (1, '我要卖车')], verbose_name='类型'),
        ),
    ]
